version: "3"

services:

  scheduler-sdk-csharp-preview-build:
    build: .
    container_name: scheduler-sdk-csharp-preview-build
    image: finbourne/scheduler-sdk-csharp-preview-build
    environment:
      - FBN_TOKEN_URL
      - FBN_USERNAME
      - FBN_PASSWORD
      - FBN_CLIENT_ID
      - FBN_CLIENT_SECRET
      - FBN_APP_NAME
      - FBN_SCHEDULER_API_URL=${FBN_BASE_API_URL}/scheduler2
      - FBN_ACCESS_TOKEN
    volumes:
      - .:/usr/src